#### general settings
name: train_small_model
model: rfdn 
scale: 4
type : mse


#### datasets
datasets:
  train:
    name: train
    mode: LQGT
    noise_needed: true
    noise_data: ../../storage/data/df2k/noise/Corrupted_noise/
    dataroot_GT: ../../storage/data/df2k/HR
    dataroot_LQ: ../../storage/data/df2k/LR
    use_shuffle: true
    n_workers: 4  # per GPU
    batch_size: 16
    GT_size: 280
    use_flip: true
    use_rot: true
    color: RGB
  val:
    name: validation
    mode: LQGT
    noise_needed: false
    noise_data: ../../storage/data/df2k/Corrupted_noise/
    dataroot_GT: ../../storage/data/df2k/HR
    dataroot_LQ: ../../storage/data/df2k/LR
    use_shuffle: false
    n_workers: 4  # per GPU
    batch_size: 1
    GT_size: 512 
    use_flip: true
    use_rot: true
    color: RGB
#in_nc=3, nf=50, num_modules=4, out_nc=3, upscale=4
#### network structures
structure:
  network_G:
    which_model_G: RFDN
    in_nc: 3
    out_nc: 3
    nf: 50
    num_modules: 4
  network_D:
    which_model_D: Discriminator
    in_nc: 3
    nf: 64

#### path
pretraining_settings:
  network_G: 
    want_load: True
    type: psnr # psnr | gan
    pretrained_model_path:  "../checkpoints/small_checkpoint_mse_noise.pt"
    strict_load: true
  network_D: 
    want_load: false
    pretrained_model_path: ../pretrained_model/RRDB_PSNR_x4.pth
    strict_load: true
  
#epoch settings
epoch_settings:
  total_epochs: 100
  resume_state_epoch: ~
  resume_state_batch: ~

#### training settings: learning rate scheme, loss
train_settings:
  lr_G: !!float 1e-4
  weight_decay_G: !!float 1e-3
  beta1_G: 0.9
  beta2_G: 0.999
  lr_D: !!float 1e-4
  weight_decay_D: !!float 1e-3
  beta1_D: 0.9
  beta2_D: 0.999
  trainer_type: psnr  # gan | psnr
  pixel_criterion: WassFeatureLoss #l1 | l2 
  pixel_weight: !!float 1e-2  # 1 if train type is psnr
  feature_criterion: l1
  tv_loss_weight: !!float 1e-5
  gan_weight: !!float 5e-3
  top_score:  !!int -1
  save_checkpoint_folder_path: "../checkpoints"
  save_checkpoint_file_name: "small_checkpoint_mse_noise"
  save_bestmodel_file_name: "small_best_mse_noise"

  load_checkpoint_file_path:  "../checkpoints/small_checkpoint_mse_noise.pt"
  sample_interval: 10

