#### general settings
name: big_model
model: srgan
distortion: sr
scale: 4

#### datasets
datasets:
  train:
    name: train
    mode: LQGT
    aug: noise
    noise_data: ./datasets/DF2K/Corrupted_noise/
    dataroot_GT: ./datasets/df2k/HR
    dataroot_LQ: ./datasets/df2k/LR
    use_shuffle: true
    n_workers: 4 
    batch_size: 64
    GT_size: 128
    use_flip: true
    use_rot: true
    color: RGB
 val:
   name: val
   mode: LQGT
   dataroot_GT: ../../../ntire20/DIV2K_valid_HR
   dataroot_LQ: ../../../ntire20/Corrupted-va-x

#### network structures
network_G:
  which_model_G: RRDBNet
  in_nc: 3
  out_nc: 3
  nf: 64
  nb: 23
network_D:
  which_model_D: discriminator
  in_nc: 3
  nf: 64

#### path
path:
  pretrain_model_G: ./saved_model/RRDB_PSNR_x4.pth
  strict_load: true
  resume_state: ~
  
#### training settings: learning rate scheme, loss
train:
  lr_G: !!float 1e-4
  weight_decay_G: 0
  beta1_G: 0.9
  beta2_G: 0.999
  lr_D: !!float 1e-4
  weight_decay_D: 0
  beta1_D: 0.9
  beta2_D: 0.999


  pixel_criterion: l1
  pixel_weight: !!float 1e-2  # 1
  feature_criterion: l1
  feature_weight: 1
  gan_type: ragan  # gan | ragan
  gan_weight: !!float 5e-3

  D_update_ratio: 1
  D_init_iters: 0

  manual_seed: 10
  val_freq: !!float 5e3
